// add
import './add/add.html';
import './add/add.js';
// bonus calculator
import './bonus/bonus.js';
import './followup/followup.css';
// followup
import './followup/followup.html';
import './followup/followUp.js';
// calendar
import './kalendar/kalendar.css';
import './kalendar/kalendar.html';
import './kalendar/kalendar.js';
// statistic
import './statistic/statistic.html';
import './statistic/StatisticMain';
import './tablet/tablet.css';
import './tablet/tablet.html';
// tablet
import './tablet/tablet.js';
import './tablet/TabletIsList.js';
import './tablet/TabletRender.js';
import './timeSelector/TimeSelector.js';
